### ISSUE TITLE
Remove transform-object-rest-spread from Gecko build

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-http.js#225]
Rest/spread is now supported in FFx55 https://bugzilla.mozilla.org/show_bug.cgi?id=1339395

**Comment by leplatrem** [comment]
```
> kinto-http@4.4.1 dist-fx /home/mathieu/Code/Mozilla/kinto-client
> BABEL_ENV=firefox browserify -s KintoHttpClient --ignore events --bare -e fx-src/index.js -o temp.jsm -t [ babelify --sourceMapRelative . ] && mkdir -p dist && cp fx-src/jsm_prefix.js dist/moz-kinto-http-client.js && echo "
/*
 * Version $npm_package_version - $(git rev-parse --short HEAD)
 */
" >> dist/moz-kinto-http-client.js && cat temp.jsm >> dist/moz-kinto-http-client.js && rm temp.jsm

SyntaxError: /home/mathieu/Code/Mozilla/kinto-client/fx-src/index.js: Unexpected token (34:28)
  32 |     const events = {};
  33 |     EventEmitter.decorate(events);
> 34 |     super(remote, { events, ...options });
     |                             ^
  35 |   }
  36 | }
  37 | 
    at Parser.pp$5.raise (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:4156:96)
    at Parser.pp$3.parseObj (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/mathieu/Code/Mozilla/kinto-client/node_modules/babylon/lib/index.js:3381:19)

```

```
npm list | grep babylon
│ ├── babylon@6.18.0
│ │ │   └── babylon@7.0.0-beta.36
│ │ ├── babylon@7.0.0-beta.36
│ ├── babylon@7.0.0-beta.36
npm ERR! peer dep missing: webpack@2 || 3, required by babel-loader@7.1.2
```

**Comment by glasserc** [comment]
You need to add the `syntax-object-rest-spread` plugin to babel instead of the `transform-object-rest-spread` one. However, I still run aground on https://github.com/browserify/browserify/issues/1802.

**Comment by goto-bus-stop** [comment]
Yep, seeing the same now. babelify adds source maps triggering the bug fixed by https://github.com/substack/node-syntax-error/pull/17, which forces using an old version of acorn. when that and https://github.com/substack/node-syntax-error/pull/20 are merged this will be fixed. going to ping substack about releasing a new `syntax-error` version in a minute.

**Comment by goto-bus-stop** [comment]
syntax-error@1.4.0 should fix https://github.com/browserify/browserify/issues/1802!
