### ISSUE TITLE
fetch is not defined in node, requires polyfill

### ISSUE THREAD

**Issue by kewisch** [Kinto/kinto-http.js#292]
STR:

1) npm install kinto-http
2) spin up a simple client that attempts to download some data

Result:

```
 ReferenceError: fetch is not defined
    at /Users/kewisch/mozilla/github/blocklistcheck/node_modules/kinto-http/lib/http.js:136:9
    at new Promise (<anonymous>)
    at HTTP.timedFetch (/Users/kewisch/mozilla/github/blocklistcheck/node_modules/kinto-http/lib/http.js:117:14)
    at HTTP._callee3$ (/Users/kewisch/mozilla/github/blocklistcheck/node_modules/kinto-http/lib/http.js:278:29)
    at tryCatch (/Users/kewisch/mozilla/github/blocklistcheck/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/kewisch/mozilla/github/blocklistcheck/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/kewisch/mozilla/github/blocklistcheck/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/kewisch/mozilla/github/blocklistcheck/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/kewisch/mozilla/github/blocklistcheck/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
```

Expected:
* works in node without hoops

More info:

Installing node-fetch and adding `var fetch = require("node-fetch");` to the beginning of http.js "fixes" the issue, so this is really just a matter of using the right polyfill on node.

I'm using node 8.11.3

**Comment by glasserc** [comment]
Hi! I'm not an expert in the NodeJS ecosystem by any stretch of the imagination, but my understanding was that the typical pattern with libraries was that they shipped without polyfills and the application using them got to choose its polyfills to make all the libraries work. Is that not true?

**Comment by Natim** [comment]
Is it possible to define dist in a npm package one for node and one for the browser so that we can have both and let it use the right one depending on the context?

**Comment by kewisch** [comment]
I managed to work around this by using `global.fetch = require("node-fetch");` before including kinto. I'm no expert on node either so I am not sure if that is the best way to go about it, but at least it works for my purposes. I'm going to close this issue now, if you feel something should be changed in kinto-http please re-open.
