### ISSUE TITLE
TypeError: Blob is not a constructor

### ISSUE THREAD

**Issue by ncloudioj** [Kinto/kinto-http.js#468]
Ran into this error when using kinto-http.js to upload attachments as follows:

```js
async function publish(collection) {
  const fileStream = fs.createReadStream(`${L10N_REPO_PATH}/all-locales`);
  const rl = readline.createInterface({
    input: fileStream,
    crlfDelay: Infinity,
  });

  for await (const line of rl) {
    const ftlPath = `${L10N_REPO_PATH}/${line}/browser/browser/newtab/asrouter.ftl`;
    if (fs.existsSync(ftlPath)) {
      const dataUri = await DataURI(ftlPath);
      try {
        await collection.addAttachment(dataUri, {id: `cfr-${VERSION}-${line}`}, {filename: "asrouter.ftl"});
      }
      catch (e) {
        console.error(e);
      }
    } else {
      console.log("Missing Fluent file for ", line);
    }
  }
}
```

The stacktrace:

```
TypeError: Blob is not a constructor
    at extractFileInfo (/Users/.../node_modules/kinto-http/lib/utils.js:459:14)
    at createFormData (/Users/.../node_modules/kinto-http/lib/utils.js:483:26)
    at Object.addAttachmentRequest (/Users/.../node_modules/kinto-http/lib/requests.js:209:44)
    at Collection._callee9$ (/Users/.../node_modules/kinto-http/lib/collection.js:664:49)
    at tryCatch (/Users/.../node_modules/regenerator-runtime/runtime.js:45:40)

```

**Comment by glasserc** [comment]
Hmm. Looks like kinto-http.js expects to be run in a browser environment. The tests run in NodeJS using `Buffer.from` (https://github.com/Kinto/kinto-http.js/blob/master/test/setup-jsdom.js#L18). I wonder if we can support both environments using something like this. It seems like the only place we use this functionality is in adding `attachment` to a `formData`. Let me try to write a PR.

**Comment by glasserc** [comment]
Closing in favor of #470, "Should we shim other browser dependencies".
